EShopOnline - Final/EShopOnline/Models/Receipt.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EShopOnline.Models
{
    public class Receipt
    {
        public int MaHD { get; set; }
        public DateTime? NgayLap { get; set; }
        public long? TongTien { get; set; }
        public string TinhTrangDonHang { get; set; }
        public string TenKH { get; set; }

        public List<Models.Receipt> GetReceipt()
        {
            List<Models.Receipt> a;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from hd in context.HoaDons
                               join kh in context.KhachHangs on hd.MaKH equals kh.MaKH
                               select new Models.Receipt
                               {
                                   MaHD = hd.MaHD,
                                   NgayLap = hd.NgayLap,
                                   TongTien = hd.TongTien,
                                   TinhTrangDonHang = hd.TinhTrangDonHang,
                                   TenKH = kh.TenKH
                               };

                a = L2EQuery.ToList();

            }
            return a;
        }
        public Receipt GetReceiptByID(int id)
        {
            Receipt a;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from hd in context.HoaDons
                               join kh in context.KhachHangs on hd.MaKH equals kh.MaKH
                               where hd.MaHD == id
                               select new Models.Receipt
                               {
                                   MaHD = hd.MaHD,
                                   NgayLap = hd.NgayLap,
                                   TongTien = hd.TongTien,
                                   TinhTrangDonHang = hd.TinhTrangDonHang,
                                   TenKH = kh.TenKH
                               };

                a = L2EQuery.SingleOrDefault();

            }
            return a;
        }
    }
}

EShopOnline - Final/EShopOnline/Models/ReceiptDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EShopOnline.Models
{
    public class ReceiptDetail
    {
        public int MaHD { get; set; }
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public int? SoLuong { get; set; }
        public long? TongTien { get; set; }
        public ReceiptDetail GetReceiptDetailByMaSP(int id)
        {
            ReceiptDetail a;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from cthd in context.ChiTietHoaDons
                               join sp in context.SanPhams on cthd.MaSP equals sp.MaSP
                               where cthd.MaSP == id
                               select new Models.ReceiptDetail
                               {
                                   MaSP = cthd.MaSP,
                                   MaHD = cthd.MaHD,
                                   TenSP = sp.TenSP,
                                   SoLuong = cthd.SoLuong,
                                   TongTien = cthd.TongTien
                               };

                a = L2EQuery.SingleOrDefault();

            }
            return a;
        }
        public List<ReceiptDetail> GetReceiptDetailByMaHD(int id)
        {
            List<ReceiptDetail> a;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from cthd in context.ChiTietHoaDons
                               join sp in context.SanPhams on cthd.MaSP equals sp.MaSP
                               where cthd.MaHD == id
                               select new Models.ReceiptDetail
                               {
                                   MaSP = cthd.MaSP,
                                   MaHD = cthd.MaHD,
                                   TenSP = sp.TenSP,
                                   SoLuong = cthd.SoLuong,
                                   TongTien = cthd.TongTien
                               };

                a = L2EQuery.ToList();

            }
            return a;
        }
    }
}

EShopOnline - Final/EShopOnline/Controllers/AdminReceiptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace EShopOnline.Controllers
{
    public class AdminReceiptController : Controller
    {
        // GET: Receipt
        public ActionResult Index()
        {
            return RedirectToAction("Receipt");
        }
        //receipt
        #region
        public ActionResult Receipt(int page = 1)
        {
            Models.Receipt rec = new Models.Receipt();
            return View(rec.GetReceipt().ToPagedList(page,2));
        }
        [HttpGet]
        public ActionResult UpdateReceipt(int id)
        {
            Models.Receipt rec = new Models.Receipt();
            return View(rec.GetReceiptByID(id));
        }
        #endregion
        //receipt detail
        #region
        public ActionResult ReceiptDetail( int id,int page = 1)
        {
            Models.ReceiptDetail recdetail = new Models.ReceiptDetail();
            return View(recdetail.GetReceiptDetailByMaHD(id).ToPagedList(page,2));
        }
        [HttpGet]
        public ActionResult UpdateReceiptDetail(int id)
        {
            Models.ReceiptDetail rec = new Models.ReceiptDetail();
            return View(rec.GetReceiptDetailByMaSP(id));
        }
        #endregion
        public ActionResult Delivery()
        {
            return View();
        }
    }
}

EShopOnline - Final/EShopOnline/Views/AdminReceipt/Delivery.cshtml
@{
    ViewBag.Title = "Delivery";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delivery</h2>

EShopOnline - Final/EShopOnline/Views/AdminReceipt/Receipt.cshtml
@model PagedList.IPagedList<EShopOnline.Models.Receipt>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Receipt";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section scripts{

}
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>Manage Receipt
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <a href="#portlet-config" data-toggle="modal" class="config">
                    </a>
                    <a href="javascript:;" class="reload">
                    </a>
                    <a href="javascript:;" class="remove">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                        <div class="col-md-6">
                            
                        </div>
                        <div class="col-md-6">
                            <div class="btn-group pull-right">
                                <button class="btn dropdown-toggle" data-toggle="dropdown">
                                    Tools <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li>
                                        <a href="#">
                                            Print
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Save as PDF
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Export to Excel
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover" id="sample_1">
                    <thead>
                        <tr>
                            <th class="table-checkbox">
                                <input value="" type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                            </th>
                            <th>
                                Tên khách hàng
                            </th>
                            <th>
                                Ngày lập
                            </th>
                            <th>
                                Tình trạng đơn hàng
                            </th>
                            <th>
                                Tổng tiền
                            </th>
                            <th>
                                Detail
                            </th>
                            <th>
                                Edit
                            </th>
                            <th>
                                Delete
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            foreach (var item in Model)
                            {
                                <tr class="odd gradeX">
                                    <td>
                                        <input type="checkbox" class="checkboxes" value="@item.MaHD" />
                                    </td>
                                    <td>
                                        @item.TenKH
                                    </td>
                                    <td>
                                        @item.NgayLap
                                    </td>
                                    <td>
                                        @item.TinhTrangDonHang
                                    </td>
                                    <td>
                                        @item.TongTien
                                    </td>
                                    <td>
                                        <a href="@Url.Action("ReceiptDetail","AdminReceipt" ,new { id = @item.MaHD})">Detail</a>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("UpdateReceipt","AdminReceipt" ,new { id = @item.MaHD})">Edit</a>
                                    </td>
                                    <td>
                                        <a class="delete" data-id="@item.MaHD" href="#">Delete</a>
                                    </td>
                                </tr>
                            }
                        }
                </table>
            </div>
            <div class="row">
                <div class="col-md-7"></div>
                <div class="col-md-5">
                    @Html.PagedListPager(Model, page => Url.Action("Receipt", new { page }))
                </div>
            </div>
        </div>
    </div>
</div>

EShopOnline - Final/EShopOnline/Views/AdminReceipt/ReceiptDetail.cshtml
@model PagedList.IPagedList<EShopOnline.Models.ReceiptDetail>
@using PagedList.Mvc;

@{
    ViewBag.Title = "ReceiptDetail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section scripts{

}
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>Manage Receipt Detail
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <a href="#portlet-config" data-toggle="modal" class="config">
                    </a>
                    <a href="javascript:;" class="reload">
                    </a>
                    <a href="javascript:;" class="remove">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                        <div class="col-md-6">

                        </div>
                        <div class="col-md-6">
                            <div class="btn-group pull-right">
                                <button class="btn dropdown-toggle" data-toggle="dropdown">
                                    Tools <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li>
                                        <a href="#">
                                            Print
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Save as PDF
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Export to Excel
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover" id="sample_1">
                    <thead>
                        <tr>
                            <th class="table-checkbox">
                                <input value="" type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                            </th>
                            <th>
                                Mã hóa đơn
                            </th>
                            <th>
                                Tên sản phẩm
                            </th>
                            <th>
                                Số lượng
                            </th>
                            <th>
                                Tổng tiền
                            </th>
                            <th>
                                Edit
                            </th>
                            <th>
                                Delete
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            foreach (var item in Model)
                            {
                                <tr class="odd gradeX">
                                    <td>
                                        <input type="checkbox" class="checkboxes" value="@item.MaSP" />
                                    </td>
                                    <td>
                                        @item.MaHD
                                    </td>
                                    <td>
                                        @item.TenSP
                                    </td>
                                    <td>
                                        @item.SoLuong
                                    </td>
                                    <td>
                                        @item.TongTien
                                    </td>
                                    
                                    <td>
                                        <a href="@Url.Action("UpdateReceiptDetail","AdminReceipt" ,new { id = @item.MaSP})">Edit</a>
                                    </td>
                                    <td>
                                        <a class="delete" data-id="@item.MaSP" href="#">Delete</a>
                                    </td>
                                </tr>
                            }
                        }
                </table>
            </div>
            <div class="row">
                <div class="col-md-7"></div>
                <div class="col-md-5">
                    @Html.PagedListPager(Model, page => Url.Action("ReceiptDetail", new { page }))
                </div>
            </div>
        </div>
    </div>
</div>

EShopOnline - Final/EShopOnline/Views/AdminReceipt/UpdateReceipt.cshtml
@model EShopOnline.Models.Receipt

@{
    ViewBag.Title = "UpdateReceipt";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>UpdateReceipt</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Receipt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.NgayLap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayLap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayLap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TongTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TongTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TongTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinhTrangDonHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TinhTrangDonHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TinhTrangDonHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EShopOnline - Final/EShopOnline/Views/AdminReceipt/UpdateReceiptDetail.cshtml
@model EShopOnline.Models.ReceiptDetail

@{
    ViewBag.Title = "UpdateReceiptDetail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>UpdateReceiptDetail</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ReceiptDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaHD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaHD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaHD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TongTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TongTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TongTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}