EShopOnline - Final/EShopOnline/Models/Brand.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EShopOnline.Models
{
    public class Brand
    {
        public int MaNSX { get; set; }
        public string TenNSX { get; set; }
        public List<Brand> GetBrand()
        {
            List<Models.Brand> brand;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from nsx in context.NhaSanXuats
                               select new Models.Brand
                               {
                                   MaNSX = nsx.MaNSX,
                                   TenNSX = nsx.TenNSX
                               };

                brand = L2EQuery.ToList();

            }
            return brand;
        }
        public Brand GetBrandByID(int id)
        {
            Brand brand;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from nsx in context.NhaSanXuats
                               where nsx.MaNSX == id
                               select new Models.Brand
                               {
                                   MaNSX = nsx.MaNSX,
                                   TenNSX = nsx.TenNSX
                               };

                brand = L2EQuery.SingleOrDefault();

            }
            return brand;
        }
        public Brand GetBrandByName(string name)
        {
            Brand brand;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from nsx in context.NhaSanXuats
                               where nsx.TenNSX == name
                               select new Models.Brand
                               {
                                   MaNSX = nsx.MaNSX,
                                   TenNSX = nsx.TenNSX
                               };

                brand = L2EQuery.SingleOrDefault();

            }
            return brand;
        }
    }
}

EShopOnline - Final/EShopOnline/Models/ImportProduct.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EShopOnline.Models
{
    public class ImportProduct
    {
        public int MaNhap { get; set; }
        public string TenSP { get; set; }
        public int? SoLuong { get; set; }
        public long? DonGia { get; set; }
        public DateTime? NgayNhap { get; set; }
        public long? TongTien { get; set; }
        public string GhiChu { get; set; }
        public List<ImportProduct> GetImportProduct()
        {
            List<Models.ImportProduct> customer;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from ip in context.NhapSanPhams
                               join sp in context.SanPhams on ip.MaSP equals sp.MaSP
                               select new Models.ImportProduct
                               {
                                   MaNhap = ip.MaNhap,
                                   TenSP = sp.TenSP,
                                   SoLuong = ip.SoLuong,
                                   DonGia = ip.DonGia,
                                   NgayNhap = ip.NgayNhap,
                                   TongTien = ip.TongTien,
                                   GhiChu = ip.GhiChu
                               };

                customer = L2EQuery.ToList();

            }
            return customer;
        }
        public ImportProduct GetImportProductByID(int id)
        {
            Models.ImportProduct importproduct;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from ip in context.NhapSanPhams
                               join sp in context.SanPhams on ip.MaSP equals sp.MaSP
                               where ip.MaNhap == id
                               select new Models.ImportProduct
                               {
                                   MaNhap = ip.MaNhap,
                                   TenSP = sp.TenSP,
                                   SoLuong = ip.SoLuong,
                                   DonGia = ip.DonGia,
                                   NgayNhap = ip.NgayNhap,
                                   TongTien = ip.TongTien,
                                   GhiChu = ip.GhiChu
                               };

                importproduct = L2EQuery.SingleOrDefault();

            }
            return importproduct;
        }
    }
}

EShopOnline - Final/EShopOnline/Models/ProductDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EShopOnline.Models
{
    public class ProductDetail
    {

        public int MaCTSP { get; set; }
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public long? GiaBan { get; set; }
        public string Hinh { get; set; }
        public string ManHinh { get; set; }
        public string HDH { get; set; }
        public string Camera { get; set; }
        public string RAM { get; set; }
        public string BoNhoTrong { get; set; }
        public string DungLuongPin { get; set; }
        public Models.ProductDetail GetProductDetailByid(int id)
        {
            Models.ProductDetail prode = new ProductDetail();
            using (var context = new BanDoDienTuEntities() )
            {
                var a = from sp in context.SanPhams
                        join ct in context.ChiTietSanPhams on sp.MaCTSP equals ct.MaCTSP
                        where sp.MaSP == id
                        select new Models.ProductDetail { MaCTSP = sp.MaCTSP, ManHinh = ct.ManHinh, HDH = ct.HDH,
                        Camera = ct.Camera, RAM = ct.RAM, BoNhoTrong = ct.BoNhoTrong, Hinh = sp.Hinh,
                        DungLuongPin = ct.DungLuongPin, TenSP = sp.TenSP, GiaBan = sp.GiaBan, MaSP = sp.MaSP};
                prode = a.SingleOrDefault();
            }
            return prode;
        }
    }
}

EShopOnline - Final/EShopOnline/Models/TypeOfProduct.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EShopOnline.Models
{
    public class TypeOfProduct
    {
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
        public List<TypeOfProduct> GetTypeOfProduct()
        {
            List<Models.TypeOfProduct> TypeOfProduct;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from lsp in context.LoaiSanPhams
                               select new Models.TypeOfProduct
                               {
                                   MaLoai = lsp.MaLoai,
                                   TenLoai = lsp.TenLoai
                               };

                TypeOfProduct = L2EQuery.ToList();

            }
            return TypeOfProduct;
        }
        public TypeOfProduct GetTypeOfProductByName(string name)
        {
            TypeOfProduct a;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from lsp in context.LoaiSanPhams
                               where lsp.TenLoai == name
                               select new Models.TypeOfProduct
                               {
                                   MaLoai = lsp.MaLoai,
                                   TenLoai = lsp.TenLoai
                               };

                a = L2EQuery.SingleOrDefault();

            }
            return a;
        }
        public TypeOfProduct GetTypeOfProductByID(int id)
        {
            TypeOfProduct a;
            using (var context = new BanDoDienTuEntities())
            {
                var L2EQuery = from lsp in context.LoaiSanPhams
                               where lsp.MaLoai == id
                               select new Models.TypeOfProduct
                               {
                                   MaLoai = lsp.MaLoai,
                                   TenLoai = lsp.TenLoai
                               };

                a = L2EQuery.SingleOrDefault();

            }
            return a;
        }
    }
}

EShopOnline - Final/EShopOnline/Controllers/AdminProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace EShopOnline.Controllers
{
    public class AdminProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return RedirectToAction("Product");
        }
        //import product
        #region 
        public ActionResult ImportProduct(int page  = 1)
        {
            Models.ImportProduct product = new Models.ImportProduct();
            return View(product.GetImportProduct().ToPagedList(page, 2));
        }
        [HttpPost]
        public JsonResult GetImportProductList()
        {
            Models.ImportProduct importproduct = new Models.ImportProduct();
            return Json(importproduct.GetImportProduct());
        }
        
        public ActionResult AddImportProduct()
        {
            Models.Product pro = new Models.Product();
            return View(pro.GetProduct());
        }
        [HttpPost]
        public ActionResult AddImportProdutcToDatabase(FormCollection form)
        {
            using (var context = new BanDoDienTuEntities())
            {
                NhapSanPham nsp = new NhapSanPham();
                nsp.MaSP = int.Parse(form["SanPham"].ToString());
                nsp.SoLuong = int.Parse(form["SoLuong"].ToString());
                nsp.DonGia = int.Parse(form["DonGia"].ToString());
                nsp.NgayNhap = DateTime.Parse(form["NgayNhap"].ToString());
                nsp.GhiChu = form["Ghichu"].ToString();
                nsp.TongTien = int.Parse(form["SoLuong"].ToString()) * int.Parse(form["DonGia"].ToString());
                context.NhapSanPhams.Add(nsp);

                
                SanPham pro = context.SanPhams.ToList<SanPham>().Where(masp => masp.MaSP == int.Parse(form["SanPham"].ToString())).FirstOrDefault<SanPham>();
                pro.SoLuongTrongKho += int.Parse(form["SoLuong"].ToString());

                context.SaveChanges();
            }
                return RedirectToAction("ImportProduct");
        }
        [HttpGet]
        public ActionResult  UpdateImportProductList(int id = 1)
        {
            Models.ImportProduct importproduct = new Models.ImportProduct();
            
            return View(importproduct.GetImportProductByID(id));
        }
        [HttpPost]
        public int DeleteImportProduct(int id)
        {
            int success = 0;
            using (var context = new BanDoDienTuEntities())
            {
                NhapSanPham deleteimportproduct = context.NhapSanPhams.Where(mansp => mansp.MaNhap == id).FirstOrDefault();
                if (deleteimportproduct != null)
                {
                    context.NhapSanPhams.Remove(deleteimportproduct);
                    success = context.SaveChanges();
                }

            }
            return success;
        }
        #endregion
        //product
        #region
        [HttpGet]
        public ActionResult Product(int page = 1)
        {
            Models.Product product = new Models.Product();
            return View(product.GetProduct().ToPagedList(page,3));
        }
        public JsonResult GetProductList()
        {
            Models.Product product = new Models.Product();
            return Json(product.GetProduct());
        }
        public JsonResult GetTypeOfProductList()
        {
            Models.TypeOfProduct Typelist = new Models.TypeOfProduct();
            return Json(Typelist.GetTypeOfProduct());
        }
        [HttpGet]
        public ActionResult UpdateProductList(int id = 1)
        {
            Models.Product product = new Models.Product();
            return View(product.GetProductByID(id));
        }
        #endregion
        //type of product
        #region
        public ActionResult TypeOfProduct(int page = 1)
        {
            Models.TypeOfProduct listtype = new Models.TypeOfProduct();
            return View(listtype.GetTypeOfProduct().ToPagedList(page,2));
        }
        public ActionResult UpdateTypeOfProduct(int id)
        {
            Models.TypeOfProduct updatetype = new Models.TypeOfProduct();
            return View(updatetype.GetTypeOfProductByID(id));
        }
        #endregion
        //brand
        #region
        public ActionResult Brand(int page = 1)
        {
            Models.Brand listbrand = new Models.Brand();
            return View(listbrand.GetBrand().ToPagedList(page,2));
        }
        public ActionResult UpdateBrand(int id)
        {
            Models.Brand updatebrand = new Models.Brand();
            return View(updatebrand.GetBrandByID(id));
        }
        #endregion
        
    }
}

EShopOnline - Final/EShopOnline/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace EShopOnline.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index(string name,int page = 1)
        {
            ViewBag.Brand = name;
            Models.Product pro = new Models.Product();
            return View(pro.GetProductByBrand(name).ToPagedList(page,6));
        }
        public ActionResult Product(string loai, string brand ,int page = 1)
        {
            ViewBag.Brand = brand;
            Models.Product pro = new Models.Product();
            return View("Index", pro.GetProductByCategoryAndBrand(loai, brand).ToPagedList(page,6));
        }
        [HttpGet]
        public ActionResult Search(string name, int page = 1)
        {
            Models.Product pro = new Models.Product();
            return View("Index", pro.SearchProduct(name).ToPagedList(page,6));
        }
    }
}

EShopOnline - Final/EShopOnline/Controllers/ProductDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EShopOnline.Controllers
{
    public class ProductDetailController : Controller
    {
        // GET: ProductDetail
        public ActionResult Index(int id)
        {
            Models.ProductDetail prode = new Models.ProductDetail(); 
           
            return View(prode.GetProductDetailByid(id));
        }
    }
}

EShopOnline - Final/EShopOnline/Views/AdminProduct/AddImportProduct.cshtml
@model IEnumerable<EShopOnline.Models.Product>

@{
    ViewBag.Title = "AddImportProduct";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>AddImportProduct</h2>

<form action="@Url.Action("AddImportProdutcToDatabase", "AdminProduct")" method="post" enctype="multipart/form-data">
    <div class="form-horizontal">
        <hr />
       
        <div class="form-group">
            <div class="col-md-2">
                <label>Tên sản phẩm</label>
                </div>
                <div class="col-md-10">
                    <select name="SanPham">
                        @{
                            foreach (var item in Model)
                            {
                                <option value="@item.MaSP">
                                    @item.TenSP
                                </option>
                            }
                        }
                        
                    </select>
                </div>
            </div>

        <div class="form-group">
                <div class="col-md-2">
                    <label>Số lượng</label>
                </div>
                <div class="col-md-10">
                    <input type="number" name="SoLuong" />
                </div>
            </div>

        <div class="form-group">
            <div class="col-md-2">
                <label>Đơn giá</label>
                </div>
                <div class="col-md-10">
                    <input type="number" name="DonGia" />
                </div>
            </div>

        <div class="form-group">
            <div class="col-md-2">
                <label>Ngày nhập</label>
                </div>
                <div class="col-md-10">
                    <input type="date" name="NgayNhap" />
                </div>
            </div>
        <div class="form-group">
            <div class="col-md-2">
                <label>Ghi chú</label>
                </div>
                <div class="col-md-10">
                    <input type="text" name="Ghichu" />
                </div>
            </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

</form>
<div style="padding:15px; background-color:aqua;">
    @Html.ActionLink("Back to List", "ImportProduct", "AdminProduct")
</div>

EShopOnline - Final/EShopOnline/Views/AdminProduct/Brand.cshtml
@model PagedList.IPagedList<EShopOnline.Models.Brand>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Brand";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@section scripts{

}
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>Manage Brand
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <a href="#portlet-config" data-toggle="modal" class="config">
                    </a>
                    <a href="javascript:;" class="reload">
                    </a>
                    <a href="javascript:;" class="remove">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="btn-group">
                                <button id="sample_editable_1_new" class="btn green">
                                    Add New <i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="btn-group pull-right">
                                <button class="btn dropdown-toggle" data-toggle="dropdown">
                                    Tools <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li>
                                        <a href="#">
                                            Print
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Save as PDF
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Export to Excel
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover" id="sample_1">
                    <thead>
                        <tr>
                            <th class="table-checkbox">
                                <input value="" type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                            </th>
                            <th>
                                Tên nhà sản xuất
                            </th>
                            <th>
                                Edit
                            </th>
                            <th>
                                Delete
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            foreach (var item in Model)
                            {
                                <tr class="odd gradeX">
                                    <td>
                                        <input type="checkbox" class="checkboxes" value="@item.MaNSX" />
                                    </td>
                                    <td>
                                        @item.TenNSX
                                    </td>

                                    <td>
                                        <a href="@Url.Action("UpdateBrand","AdminProduct" ,new { id = @item.MaNSX})">Edit</a>
                                    </td>
                                    <td>
                                        <a class="delete" data-id="@item.MaNSX" href="#">Delete</a>
                                    </td>

                                </tr>
                            }
                        }
                </table>
            </div>
            <div class="row">
                
                <div class="col-md-12">
                    @Html.PagedListPager(Model, page => Url.Action("Brand", new { page }))
                </div>
            </div>
        </div>
    </div>
</div>

EShopOnline - Final/EShopOnline/Views/AdminProduct/ImportProduct.cshtml
@model PagedList.IPagedList<EShopOnline.Models.ImportProduct>
@using PagedList.Mvc;
@{
    ViewBag.Title = "ImportProduct";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@section scripts{
    
    }
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>Manage Import Product
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <a href="#portlet-config" data-toggle="modal" class="config">
                    </a>
                    <a href="javascript:;" class="reload">
                    </a>
                    <a href="javascript:;" class="remove">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="btn-group">
                                <a href="@Url.Action("AddImportProduct","AdminProduct")">
                                    <button id="sample_editable_1_new" class="btn green">
                                        Add New <i class="fa fa-plus"></i>
                                    </button>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="btn-group pull-right">
                                <button class="btn dropdown-toggle" data-toggle="dropdown">
                                    Tools <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li>
                                        <a href="#">
                                            Print
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Save as PDF
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Export to Excel
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover" id="sample_1">
                    <thead>
                        <tr>
                            <th class="table-checkbox">
                                <input value="" type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                            </th>
                            <th>
                                Tên sản phẩm
                            </th>
                            <th>
                                Ngày nhập
                            </th>
                            <th>
                                Số lượng 
                            </th>
                            <th>
                                Đơn giá
                            </th>
                            <th>
                                Tổng tiền
                            </th>
                            <th>
                                Ghi chú
                            </th>
                            <th>
                                Edit
                            </th>
                            <th>
                                Delete
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            foreach (var item in Model)
                            {
                                <tr class="odd gradeX">
                                    <td>
                                        <input type="checkbox" class="checkboxes" value="@item.MaNhap" />
                                    </td>
                                    <td>
                                        @item.TenSP
                                    </td>
                                    <td>
                                        @item.NgayNhap
                                    </td>
                                    <td>
                                        @item.SoLuong
                                    </td>
                                    <td class="center">
                                        @item.DonGia
                                    </td>
                                    <td>
                                        @item.TongTien
                                    </td>
                                    <td>
                                        @item.GhiChu
                                    </td>
                                    <td>
                                       <a href="@Url.Action("UpdateImportProductList","AdminProduct" ,new { id = @item.MaNhap})" >Edit</a>
                                    </td>
                                    <td>
                                       <a class="delete" data-id="@item.MaNhap" href="#">Delete</a>
                                    </td>
                                   
                                </tr>
                            }
                        }
                </table>
            </div>
            <div class="row">
                <div class="col-md-10"></div>
                <div class="col-md-2">
                    @Html.PagedListPager(Model, page => Url.Action("ImportProduct", new { page }))
                </div>
            </div>
        </div>
    </div>
</div>

EShopOnline - Final/EShopOnline/Views/AdminProduct/ProductDetail.cshtml
@{
    ViewBag.Title = "ProductDetail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>ProductDetail</h2>

EShopOnline - Final/EShopOnline/Views/AdminProduct/UpdateBrand.cshtml
@model EShopOnline.Models.Brand

@{
    ViewBag.Title = "UpdateBrand";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>UpdateBrand</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        <div class="form-group">
            @Html.LabelFor(model => model.TenNSX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNSX, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNSX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Brand")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EShopOnline - Final/EShopOnline/Views/AdminProduct/UpdateTypeOfProduct.cshtml
@model EShopOnline.Models.TypeOfProduct

@{
    ViewBag.Title = "UpdateTypeOfProduct";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>UpdateTypeOfProduct</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TypeOfProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "TypeOfProduct")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}